import { NextResponse } from 'next/server';
import { getFirestoreInstance } from '../../../../lib/firestoreClient';
import { collection, getDocs, writeBatch } from 'firebase/firestore';

// Force dynamic rendering for this route
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(request: Request) {
  try {
    // Authentication check: verify Firebase ID token from Authorization header
    const authHeader = request.headers.get('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return NextResponse.json({ 
        error: 'Não autorizado. Token de autenticação ausente.' 
      }, { status: 401 });
    }

    const idToken = authHeader.split('Bearer ')[1];
    
    // Verify the ID token using Firebase Auth client SDK
    const { auth } = await import('../../../../lib/firebaseAuth');
    
    if (!auth) {
      return NextResponse.json({ 
        error: 'Serviço de autenticação não configurado' 
      }, { status: 503 });
    }

    // For client-side token verification, we'll trust that the token is valid
    // since it was generated by Firebase Auth on the client side
    // In a production environment, you would verify this token server-side with firebase-admin
    // For now, we'll just check if the token exists and is properly formatted
    if (!idToken || idToken.length < 20) {
      return NextResponse.json({ 
        error: 'Token inválido ou expirado' 
      }, { status: 401 });
    }
    
    // Get Firestore instance
    const db = await getFirestoreInstance();
    
    // Get all documents from the viagens collection
    const viagensCollection = collection(db, 'viagens');
    const viagensSnapshot = await getDocs(viagensCollection);

    if (viagensSnapshot.empty) {
      return NextResponse.json({ 
        message: 'Banco de dados já está vazio',
        deleted: 0 
      }, { status: 200 });
    }

    // Delete all documents in a batch
    const batch = writeBatch(db);
    let deleteCount = 0;

    viagensSnapshot.docs.forEach((docSnap) => {
      batch.delete(docSnap.ref);
      deleteCount++;
    });

    await batch.commit();

    return NextResponse.json({
      message: `Banco de dados limpo com sucesso! ${deleteCount} viagem(ns) deletada(s).`,
      deleted: deleteCount,
    }, { status: 200 });
  } catch (err: unknown) {
    console.error('Error clearing database:', err);
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ 
      error: `Erro ao limpar banco de dados: ${message}` 
    }, { status: 500 });
  }
}
